# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Master Server
  config.vm.define "k8s-master" do |k8s-master|
    k8s-master.vm.box = "ubuntu/xenial64"
    k8s-master.vm.hostname = "k8s-master.example.com"
    k8s-master.vm.network "private_network", ip: "172.31.0.100"
    k8s-master.vm.provider "virtualbox" do |v|
      v.name = "k8s-master"
      v.memory = 4048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    #k8s-master.vm.provision "shell", path: "bootstrap_k8s-master.sh"
  end

  NodeCount = 2

  # Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "k8s-worker#{i}" do |k8s-workernode|
      k8s-workernode.vm.box = "ubuntu/xenial64"
      k8s-workernode.vm.hostname = "k8s-worker#{i}.example.com"
      k8s-workernode.vm.network "private_network", ip: "172.31.0.10#{i}"
      k8s-workernode.vm.provider "virtualbox" do |v|
        v.name = "k8s-worker#{i}"
        v.memory = 1024
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      #k8s-workernode.vm.provision "shell", path: "bootstrap_k8s-worker.sh"
    end
  end

end
